version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: podcast_db
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - podcast_data:/var/lib/postgresql/data

volumes:
  podcast_data:
